// default package
// Generated 30 jun. 2021 19:58:00 by Hibernate Tools 5.2.12.Final
package com.david.eurocopa.models.entity;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;


import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Selecciones generated by hbm2java
 */
@Entity
@Table(name = "selecciones")
public class Selecciones implements java.io.Serializable {

	
	private static final long serialVersionUID = 1L;
	private String id;
	private String nombre;
	@JsonManagedReference
	private Set<Jugador> jugadors = new HashSet<Jugador>(0);
	
	public Selecciones() {
	}

	public Selecciones(String id, String nombre) {
		this.id = id;
		this.nombre = nombre;
	}

	public Selecciones(String id, String nombre, Set<Jugador> jugadors) {
		this.id = id;
		this.nombre = nombre;
		this.jugadors = jugadors;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "selecciones")
	public Set<Jugador> getJugadors() {
		return this.jugadors;
	}
	
	
	public void setJugadors(Set<Jugador> jugadors) {
		this.jugadors = jugadors;
	}

}
